name: nimona
description: Flutter bindings for nimona
version: 0.0.1
homepage: https://github.com/nimona/flutter-nimona

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3

dev_dependencies:
  ffigen: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: NimonaPlugin
