name: nimona
description: Flutter bindings for nimona
version: 0.2.3
homepage: https://github.com/nimona/flutter-nimona

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  path_provider: ^2.0.1
  flutter:
    sdk: flutter
  ffi: ^1.0.0

dev_dependencies:
  ffigen: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: NimonaPlugin
      ios:
        pluginClass: NimonaPlugin
      linux:
        pluginClass: NimonaPlugin
      windows:
        pluginClass: NimonaPlugin
